config/routes.rb
Rails.application.routes.draw do
  resources :podcasts

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: [:show, :edit, :update, :destroy]

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1
  # PATCH/PUT /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast.destroy
    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: 'Podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def podcast_params
      params.require(:podcast).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodcastTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/podcasts/_form.html.haml
= form_for @podcast do |f|
  - if @podcast.errors.any?
    #error_explanation
      %h2= "#{pluralize(@podcast.errors.count, "error")} prohibited this podcast from being saved:"
      %ul
        - @podcast.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/podcasts/edit.html.haml
%h1 Editing podcast

= render 'form'

= link_to 'Show', @podcast
\|
= link_to 'Back', podcasts_path

app/views/podcasts/index.html.haml
%h1 Listing podcasts

%table
  %tr
    %th Title
    %th Url
    %th
    %th
    %th

  - @podcasts.each do |podcast|
    %tr
      %td= podcast.title
      %td= podcast.url
      %td= link_to 'Show', podcast
      %td= link_to 'Edit', edit_podcast_path(podcast)
      %td= link_to 'Destroy', podcast, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Podcast', new_podcast_path

app/views/podcasts/new.html.haml
%h1 New podcast

= render 'form'

= link_to 'Back', podcasts_path

app/views/podcasts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @podcast.title
%p
  %b Url:
  = @podcast.url

= link_to 'Edit', edit_podcast_path(@podcast)
\|
= link_to 'Back', podcasts_path